package qwenimage

import (
	"encoding/binary"
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"
)

// fixturesDir points at the parity fixtures generated by reference/harness.py.
func fixturesDir(t *testing.T) string {
	t.Helper()
	dir := filepath.Join("reference", "fixtures")
	if _, err := os.Stat(dir); err != nil {
		t.Skipf("fixtures not generated (run reference/harness.py): %v", err)
	}
	return dir
}

type fixtureMeta struct {
	Shape []int  `json:"shape"`
	Dtype string `json:"dtype"`
}

// loadFixture reads a raw float32 .bin + JSON sidecar fixture pair.
func loadFixture(t *testing.T, name string) ([]float32, []int) {
	t.Helper()
	dir := fixturesDir(t)
	metaBytes, err := os.ReadFile(filepath.Join(dir, name+".json"))
	if err != nil {
		t.Skipf("fixture %s not present: %v", name, err)
	}
	var meta fixtureMeta
	if err := json.Unmarshal(metaBytes, &meta); err != nil {
		t.Fatalf("fixture %s: bad sidecar: %v", name, err)
	}
	raw, err := os.ReadFile(filepath.Join(dir, name+".bin"))
	if err != nil {
		t.Fatalf("fixture %s: missing bin: %v", name, err)
	}
	if len(raw)%4 != 0 {
		t.Fatalf("fixture %s: bin size %d not a multiple of 4", name, len(raw))
	}
	vals := make([]float32, len(raw)/4)
	for i := range vals {
		vals[i] = math.Float32frombits(binary.LittleEndian.Uint32(raw[i*4:]))
	}
	want := 1
	for _, d := range meta.Shape {
		want *= d
	}
	if want != len(vals) {
		t.Fatalf("fixture %s: shape %v (=%d) disagrees with %d values", name, meta.Shape, want, len(vals))
	}
	return vals, meta.Shape
}

// maxAbsDiff returns the maximum absolute elementwise difference.
func maxAbsDiff(t *testing.T, got, want []float32) float64 {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("length mismatch: got %d want %d", len(got), len(want))
	}
	var m float64
	for i := range got {
		d := math.Abs(float64(got[i]) - float64(want[i]))
		if d > m {
			m = d
		}
	}
	return m
}

func equalShape(a, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
